spring.application.name=Receipt Splitter Backend

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5432/receipt_splitter
spring.datasource.username=rs_user
spring.datasource.password=rs_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL INIT
spring.sql.init.mode=never