apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-splitter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receipt-splitter
  template:
    metadata:
      labels:
        app: receipt-splitter
    spec:
      containers:
        - name: receipt-splitter
          image: receiptsplitter.azurecr.io/receipt-splitter:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_PASSWORD